version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: finance-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-financebot}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty123}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance_bot_network

networks:
  finance_bot_network:
    name: finance_bot_network
    driver: bridge
    internal: false

volumes:
  postgres_data:
